### ISSUE TITLE
Unable to find image 'gaudi/db' locally

### ISSUE THREAD

**Issue by ZAYEC77** [marmelab/gaudi#90]
I had error when run `gaudi`:

```
Unable to find image 'gaudi/db' locally
Pulling repository gaudi/db
2015/03/11 09:20:49 HTTP code: 404
```

gaudi version is `0.2.1`

**Comment by manuquentin** [comment]
Hello,
Gaudi is not maintained anymore, it was build for docker <= 1.0, I think your issue is due to your version of docker.

Natives solutions like [docker-compose](https://docs.docker.com/compose/) have supersede gaudi.

**Comment by ZAYEC77** [comment]
@manuquentin thanks
